---
  - name: Change root password
    mysql_user: name=root password={{ db_root_pass }} login_user=root login_password={{ db_root_pass }} check_implicit_admin=yes priv=*.*:ALL,GRANT state=present

  - name: Create MySQL production database
    mysql_db: name={{ db_name }} state=present login_user=root login_password={{ db_root_pass }}

  - name: Create MySQL testing database
    mysql_db: name={{ db_name }}_dev state=present login_user=root login_password={{ db_root_pass }}

  - name: Create database user
    mysql_user: name={{ db_user }} password={{ db_password}} login_user=root login_password={{ db_root_pass }} priv={{ db_name }}.*:ALL,GRANT state=present

  - name: Update user privleges
    mysql_user: name={{db_user}} login_user=root login_password={{ db_root_pass }} append_privs=true priv={{db_name}}_dev.*:ALL,GRANT state=present